### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Tharunkumar01** [pycaret/sktime-dev-days-2021#2]
ImportError: cannot import name '_raise_dep_warning_if_not_pytest' from 'sklearn.utils.deprecation' (/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py)

**Comment by Tharunkumar01** [comment]
I reinstalled the package it's solved the problem

**Comment by ngupta23** [comment]
@Tharunkumar01   I see you reopened it. Does the issue still exist?

**Comment by Tharunkumar01** [comment]
I just want to hear that why did it show in the first call

**Comment by ngupta23** [comment]
First install might not have been clean. Did you install second time in a fresh environment?

**Comment by Tharunkumar01** [comment]
I tried to install it on the Kaggle environment. Maybe you are right, after restarting the notebook it ran successfully
